title: Bruna Moreira # name of the site
author: Bruna Moreira # name of site's author
email: brunanayaramlima@gmail.com # email of site's author
url: https://BrunaNayara.github.io # root address of the site
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote-theme: riggraz/no-style-please #no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
